### ISSUE TITLE
add support for avro deserialization

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/kafkatail#11]
**As a** developer
**I want to** tail avro messages pushed to kafka
**So that** I can view avro binary data in plaintext and make sense out of it

**Challenges**:
Currently none of the go library supporst native avro serialization in kafka messages. So our `go` integration-test will
not be accurate. It needs to be written in language which does support native kafka based avro messages in kafka
- [x] PoC with `aruba-cucumber`
- [x] Analysis: is there any lib which can deserialize kafka-avro messages in go
  + for current usecase `linkedin/goavro` should work
  + ~`github.com/hamba/avro` seems much simpler than `linkedin/avro`. using this for now~
    * This lib doesn't support recursive avro struct. Need to use `linkedin/goavro`. Sample [playground](https://go.dev/play/p/lxDoGD1tQjA)

There is already #13 planned which will add the support for protobuf and avro schema registries. For now implementing avro de-serialization with `ByteSerializer` messages should work. 

### Assumption:
- Avro messages are pushed to kafka with `ByteSerializer` without having confluent-schema-registry.  

### Scope
- add support of value de-serialization for avro message
- add new wire-format=avro
- decode only `ByteSerialized` avro-messages to plaintext

### Tasks
- [ ] add feature file for avro messages
- [x] add support for `wire_format=avro`
- [ ] add support for decoding based on avro schema provided via cli flag
- [ ] update README.md with correct exampld

**Comment by HandOfGod94** [comment]
#### Tasks for using `aruba` for integration test
- [x] add supported commands feature files
- [x] add tasks in Makefile for running cucumber tests
- [x] update README.md developer notes
- [x] add ci job to run cucumber tests
