### ISSUE TITLE
support json as output format

### ISSUE THREAD

**Issue by HandOfGod94** [HandOfGod94/kafkatail#8]
**As a** developer
**I want** to print binary encoded messages as `json`
**So that** I can filter out messages using `jq`

### Tasks
- [ ] add `--out` flag. possible values: `json,text`
- [ ] shorthand flag `-o`
- [ ] add new flag to suppress logging messages
- [ ] print json formatted message for `proto` type
- [ ] add integration tests
